package com.wsm.cxf.doemp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-01-11T19:32:11.721+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "DoEmpService", 
                  wsdlLocation = "http://localhost:8080/cxf02/service/doemp?wsdl",
                  targetNamespace = "http://www.wsm.com/cxf/doemp") 
public class DoEmpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.wsm.com/cxf/doemp", "DoEmpService");
    public final static QName DoEmpPort = new QName("http://www.wsm.com/cxf/doemp", "DoEmpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf02/service/doemp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DoEmpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxf02/service/doemp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DoEmpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DoEmpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoEmpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoEmpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoEmpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoEmpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IDoEmp
     */
    @WebEndpoint(name = "DoEmpPort")
    public IDoEmp getDoEmpPort() {
        return super.getPort(DoEmpPort, IDoEmp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDoEmp
     */
    @WebEndpoint(name = "DoEmpPort")
    public IDoEmp getDoEmpPort(WebServiceFeature... features) {
        return super.getPort(DoEmpPort, IDoEmp.class, features);
    }

}
