package com.wsm.cxf.dodept;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-01-11T18:49:15.443+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "DoDeptService", 
                  wsdlLocation = "http://localhost:8080/cxf02/service/dodept?wsdl",
                  targetNamespace = "http://www.wsm.com/cxf/dodept") 
public class DoDeptService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.wsm.com/cxf/dodept", "DoDeptService");
    public final static QName DoDeptPort = new QName("http://www.wsm.com/cxf/dodept", "DoDeptPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf02/service/dodept?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DoDeptService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxf02/service/dodept?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DoDeptService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DoDeptService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoDeptService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoDeptService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoDeptService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoDeptService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IDoDept
     */
    @WebEndpoint(name = "DoDeptPort")
    public IDoDept getDoDeptPort() {
        return super.getPort(DoDeptPort, IDoDept.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDoDept
     */
    @WebEndpoint(name = "DoDeptPort")
    public IDoDept getDoDeptPort(WebServiceFeature... features) {
        return super.getPort(DoDeptPort, IDoDept.class, features);
    }

}
