package com.wsm.cxf.dodept;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-01-11T18:49:15.393+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.wsm.com/cxf/dodept", name = "IDoDept")
@XmlSeeAlso({ObjectFactory.class})
public interface IDoDept {

    @WebMethod
    @RequestWrapper(localName = "find", targetNamespace = "http://www.wsm.com/cxf/dodept", className = "com.wsm.cxf.dodept.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://www.wsm.com/cxf/dodept", className = "com.wsm.cxf.dodept.FindResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.wsm.cxf.dodept.Dept find(
        @WebParam(name = "deptno", targetNamespace = "http://www.wsm.com/cxf/dodept")
        int deptno
    );
}
